



  export const data = [

    {
      "id": 1,
       "category":"A-Class",
       "product": "Mercedes Benz A-Class Limousine",
       "image": "https://res.cloudinary.com/dphjq0s9o/image/upload/v1635834131/samples/ecommerce/cars/GLA-2_ks9wud.jpg",
       "desc": "Mercedes-Benz has for the first time launched the A-Class Limousine in Uganda and it is presently offered in three different variants. This is the 12th car and 2nd AMG model to be locally manufactured by the German luxury automaker",
       "price": 100,
       "Mileage":"17-21 kmpl",
       "engine": "1332 to 19950 cc",
       "Transmission": "Automatic",
       "Fuel Type":" Deisel Petrol",
       "Seating Capacity":" 5 Seater"
     },
     {
      "id": 2,
       "category":"A-Class",
       "product": "Mercedes Benz GLA",
       "image": "https://res.cloudinary.com/dphjq0s9o/image/upload/v1635834130/samples/ecommerce/cars/GLE-3_lgdzge.jpg",
       "desc": "Mercedes-Benz has introduced the latest updated iteration of the GLA crossover in Uganda. Showcased previously at the 2020 Auto Expo, the entry-level SUV from the German carmaker is finally here.",
       "price": 90,
       "Mileage":"17-21 kmpl",
       "engine": "1332 to 1950cc",
       "Transmission": "Automatic",
       "Fuel Type":" Deisel Petrol",
       "Seating Capacity":" 5 Seater"
     },
      {
        "id": 3,
        "category":"C-Class",
        "product": "Mercedes Benz C Class",
        "image": "https://res.cloudinary.com/dphjq0s9o/image/upload/v1635834134/samples/ecommerce/cars/benzC-1_fbxien.jpg",
        "desc": "The refreshed Mercedes-Benz C-Class arrives in Uganda with a mid-life update",
        "price": 150,
        "Mileage":"14 - 16 kmpl",
        "engine": "1950 to 1991 cc",
        "Transmission": "Automatic",
        "Fuel Type":" Deisel Petrol",
        "Seating Capacity":"4 Seater"
     }, 
     {
      "id": 4,
      "category":"A-Class",
      "product": "Mercedes Benz AMG 35 Limousine",
      "image": "https://res.cloudinary.com/dphjq0s9o/image/upload/v1635834129/samples/ecommerce/cars/AMG_zxvzjo.jpg",
      "desc": "German luxury automaker BMW has for the first time launched the A-Class Limousine in Uganda and it also comes with an AMG A35 4Matic.",
      "price": 200,
      "Mileage":"13 kmpl",
      "engine": "1991 cc",
      "Transmission": "Automatic",
      "Fuel Type":" Petrol",
      "Seating Capacity":" 5 Seater"
      },
      {
        "id": 5,
        "category":"A-Class",
        "product": "Mercedes Benz GLC Class",
        "image":"https://res.cloudinary.com/dphjq0s9o/image/upload/v1635834135/samples/ecommerce/cars/GLC-1_sxa9aj.jpg",
        "desc": "The popular selling SUV from Mercedes-Benz, the GLC is available in two trims and six colour options.",
        "price": 180,
        "Mileage":"14 kmpl",
        "engine": "1950 to 1991 cc",
        "Transmission": "Automatic",
        "Fuel Type":" Deisel Petrol",
        "Seating Capacity":" 5 Seater"
      },
      {
        "id": 6,
        "category":"A-Class",
        "product": "Mercedes Benz AMG GLA35",
        "image": "https://res.cloudinary.com/dphjq0s9o/image/upload/v1635834132/samples/ecommerce/cars/GLC-3_jjaqoj.jpg",
        "desc": "Mercedes-Benz has expanded the performance-focussed product lineup in India with the AMG GLA 35 4M",
        "price": 120,
        "Mileage":"13 kmpl",
        "engine": "1991 cc",
        "Transmission": "Automatic",
        "Fuel Type":" Petrol",
        "Seating Capacity":" 5 Seater"
      },
      {
        "id": 7,
       "category":"E-Class",
       "product": "Mercedes Benz E Class",
       "image": "https://res.cloudinary.com/dphjq0s9o/image/upload/v1635834132/samples/ecommerce/cars/GLC-3_jjaqoj.jpg",
       "desc": "Mercedes-Benz has introduced the E-Class facelift in Uganda",
       "price": 200,
       "Mileage":"17 kmpl",
       "engine": "1950 to 2925 cc",
       "Transmission": "Automatic",
       "Fuel Type":" Deisel Petrol",
       "Seating Capacity":" 5 Seater"
      },
      {
        "id": 8,
       "category":"G-Class",
       "product": "Mercedes Benz GLC Coupe",
       "image": "https://res.cloudinary.com/dphjq0s9o/image/upload/v1635834129/samples/ecommerce/cars/benzC-8_n4evo9.jpg",
       "desc": "The Mercedes-Benz GLC Coupe is targeted at those who want a five-seater SUV with a bit of panache",
       "price": 120,
       "Mileage":"7 kmpl",
       "engine": "1950 to 1991 cc",
       "Transmission": "Automatic",
       "Fuel Type":" Deisel Petrol",
       "Seating Capacity":" 5 Seater"
      },



      {
        "id": 9,
        "category":"V-Class",
        "product": "Mercedes Benz V-Class",
        "image": "https://res.cloudinary.com/dphjq0s9o/image/upload/v1635834131/samples/ecommerce/cars/benzC-4_qjqjqc.jpg",
        "desc": "Mercedes-Benz V-Class is available in Uganda in two variants – Expression and Exclusive",
        "price": 200,
        "Mileage":"17-21 kmpl",
        "engine": "1950 cc",
        "Transmission": "Automatic",
        "Fuel Type":" Diesel ",
        "Seating Capacity":" 7 Seater"
      },
      {
        "id": 10,
        "category":"A-Class",
        "product": "Mercedes Benz GLA",
        "image": "https://res.cloudinary.com/dphjq0s9o/image/upload/v1635834135/samples/ecommerce/cars/GLC-1_sxa9aj.jpg",
        "desc": "The second-generation Mercedes-Benz GLE SUV is available in a long wheel base version in Uganda",
        "price": 350,
        "Mileage":"11 - 14 kmpl",
        "engine": "1950 to 2999 cc",
        "Transmission": "Automatic",
        "Fuel Type":" Diesel Petrol",
        "Seating Capacity":" 5 Seater"
      },
      {
        "id": 11,
        "category":"A-Class",
        "product": " Mercedes Benz C Coupe",
        "image": "https://res.cloudinary.com/dphjq0s9o/image/upload/v1635834132/samples/ecommerce/cars/benzV-1_zfvy77.jpg",
        "desc": "Mercedes-AMG C43 Coupe has further strengthened its foothold in the country with the launch of the C43 AMG coupe.",
        "price": 200,
        "Mileage":"7 kmpl",
        "engine": "2996 to 3982 cc",
        "Transmission": "Automatic",
        "Fuel Type":" Petrol",
        "Seating Capacity":" 4 Seater"
      },
      {
        "id": 12,
       "category":" G-Class",
       "product": "Mercedes Benz AMG GLC 43 Coupe",
       "image": "https://res.cloudinary.com/dphjq0s9o/image/upload/v1635834134/samples/ecommerce/cars/benzA-1_mf6urv.jpg",
       "desc": "The locally assembled Mercedes-Benz GLC 43 AMG 4MATIC Coupe has made its debut in Uganda",
       "price": 150,
       "Mileage":"9 kmpl",
       "engine": "2996 cc",
       "Transmission": "Automatic",
       "Fuel Type":"  Petrol",
       "Seating Capacity":" 5 Seater"
      },
      {
        "id": 13,
        "category":"A-Class",
        "product": "Mercedes Benz CLS",
        "image": "https://res.cloudinary.com/dphjq0s9o/image/upload/v1635834130/samples/ecommerce/cars/benzE-2_j7zsuj.jpg",
        "desc": "Mercedes-Benz has officially launched the third generation CLS-Class in a single 300d variant",
        "price": 100,
        "Mileage":"12 kmpl",
        "engine": "1950 cc",
        "Transmission": "Automatic",
        "Fuel Type":" Diesel ",
        "Seating Capacity":" 5 Seater"
      },
      {
        "id": 14,
        "category":"E-Class",
        "product": "Mercedes Benz AMG E53",
        "image": "https://res.cloudinary.com/dphjq0s9o/image/upload/v1635834135/samples/ecommerce/cars/GLC-1_sxa9aj.jpg",
        "desc": "The Mercedes-Benz E53 4Matic+ has joined the AMG-spec E-Class line-up for the first time in Uganda",
        "price": 250,
        "Mileage":"11 kmpl",
        "engine": "2999 cc",
        "Transmission": "Automatic",
        "Fuel Type":" Petrol ",
        "Seating Capacity":" 5 Seater"
      },
      {
        "id": 15,
        "category":"E-Class",
        "product": "Mercedes Benz EQC",
        "image": "https://res.cloudinary.com/dphjq0s9o/image/upload/v1635834131/samples/ecommerce/cars/EQL-2_bl1nja.jpg",
        "desc": "The Mercedes-Benz EQC electric SUV has been launched in Uganda",
        "price": 300,
        "Mileage":"6 kmpl",
        "engine": "2990 cc",
        "Transmission": "Automatic",
        "Fuel Type":"Electric ",
        "Seating Capacity":" 5 Seater"
      },
      {
        "id": 16,
        "category":"G-Class",
        "product": " Mercedes Benz GLS",
        "image": "https://res.cloudinary.com/dphjq0s9o/image/upload/v1635834141/samples/ecommerce/cars/GLC-4_kmgxlf.jpg",
        "desc": "The Mercedes-Benz GLS is underpinned by the company's new Modular High Architecture (MHA) that also underpins the new GLE",
        "price": 300,
        "Mileage":"10 - 12 kmpl",
        "engine": "2925 to 2999 cc",
        "Transmission": "Automatic",
        "Fuel Type":"Diesel Petrol ",
        "Seating Capacity":" 7 Seater"
      },
      {
        "id": 17,
        "category":"G-Class",
        "product": " Mercedes Benz G Class",
        "image": "https://res.cloudinary.com/dphjq0s9o/image/upload/v1635834131/samples/ecommerce/cars/GLC-2_jj5gdx.jpg",
        "desc": "Mercedes-AMG G63 is available in a single top of the line model in Uganda",
        "price": 250,
        "Mileage":"6 - 9 kmpl",
        "engine": "2925 to 3982 cc",
        "Transmission": "Automatic",
        "Fuel Type":"Diesel Petrol ",
        "Seating Capacity":" 5 Seater"
      },
      {
        "id": 18,
        "category":"G-Class",
        "product": "Mercedes Benz AMG E63",
        "image": "https://res.cloudinary.com/dphjq0s9o/image/upload/v1635834135/samples/ecommerce/cars/GLC-3_qjqjqe.jpg",
        "desc": "The second generation model strikes a right balance between its conventional styling elements along with the modern design.",
        "price": 450,
        "Mileage":" 9 kmpl",
        "engine": "2900 to 3982 cc",
        "Transmission": "Automatic",
        "Fuel Type":" Petrol ",
        "Seating Capacity":" 4 Seater"
      },
      {
        "id": 19,
        "category":"G-Class",
        "product": "Mercedes Benz S-Class",
        "image": "https://res.cloudinary.com/dphjq0s9o/image/upload/v1635834131/samples/ecommerce/cars/GLC-5_qjqjqe.jpg",
        "desc": "The Mercedes-Benz GLS is underpinned by the company's new Modular High Architecture (MHA) that also underpins the new GLE",
        "price": 200,
        "Mileage":" 10 kmpl",
        "engine": "2925 to 3982 cc",
        "Transmission": "Automatic",
        "Fuel Type":"Diesel Petrol ",
        "Seating Capacity":" 5 Seater"
      },
      {
      "id": 20,
      "category":"A-Class",
      "product": " Mercedes Benz S-Class W222",
      "image": "https://res.cloudinary.com/dphjq0s9o/image/upload/v1635834139/samples/ecommerce/cars/GLS-1_brshqv.jpg",
      "desc": "German luxury automaker BMW has for the first time launched the A-Class Limousine in Uganda and it also comes with an AMG A35 4Matic.",
      "price": 180,
      "Mileage":"20 kmpl",
      "engine": "2991 cc",
      "Transmission": "Automatic",
      "Fuel Type":" Petrol",
      "Seating Capacity":" 5 Seater"
      },
      {
        "id": 21,
        "category":"A-Class",
        "product": " Mercedes Benz S-Class W222",
        "image": "https://res.cloudinary.com/dphjq0s9o/image/upload/v1635834136/samples/ecommerce/cars/GLS-2_zfhxaa.jpg",
        "desc": "German luxury automaker BMW has for the first time launched the A-Class Limousine in Uganda and it also comes with an AMG A35 4Matic.",
        "price": 350,
        "Mileage":"20 kmpl",
        "engine": "2991 cc",
        "Transmission": "Automatic",
        "Fuel Type":" Petrol",
        "Seating Capacity":" 5 Seater"
      },
      {
        "id": 22,
        "category":"A-Class",
        "product": " Mercedes Benz Maybach GLS",
        "image": "https://res.cloudinary.com/dphjq0s9o/image/upload/v1635834133/samples/ecommerce/cars/CLS-1_vfpr51.jpg",
        "desc": "German luxury automaker BMW has for the first time launched the A-Class GLS in Uganda and it also comes with an AMG A35 4Matic.",
        "price": 250,
        "Mileage":"17-20 kmpl",
        "engine": "2000 to 2991 cc",
        "Transmission": "Automatic",
        "Fuel Type":" Petrol",
        "Seating Capacity":" 5 Seater"
      },
      {
        "id": 23,
        "category":"A-Class",
        "product": " Mercedes Benz AMG GT 4-Door Coupe",
        "image": "https://res.cloudinary.com/dphjq0s9o/image/upload/v1635834135/samples/ecommerce/cars/GLE-2_sjjour.jpg",
        "desc": "German luxury automaker BMW has for the first time launched the  Mercedes Benz AMG GT 4-Door Coupe in Uganda and it also comes with an AMG A35 4Matic.",
        "price": 150,
        "Mileage":"6-9 kmpl",
        "engine": "2900 to 2991 cc",
        "Transmission": "Automatic",
        "Fuel Type":" Petrol Diesel",
        "Seating Capacity":" 4 Seater"
      },
      {
        "id": 24,
        "category":"A-Class",
        "product": " Mercedes Benz AMG GT",
        "image": "https://res.cloudinary.com/dphjq0s9o/image/upload/v1635834130/samples/ecommerce/cars/GLE-3_lgdzge.jpg",
        "desc": "German luxury automaker BMW has for the first time launched the  Mercedes Benz AMG GT  in Uganda and it also comes with an AMG A35 4Matic.",
        "price": 350,
        "Mileage":"10 kmpl",
        "engine": "2900 to 4991 cc",
        "Transmission": "Automatic",
        "Fuel Type":" Petrol ",
        "Seating Capacity":" 2 Seater"
      }



      
  ]